### ISSUE TITLE
Avoid panic if SetTestCodeFromCallerSkip function arguments are not correct

### ISSUE THREAD

**Issue by drodriguezhdez** [undefinedlabs/scope-go-agent#219]
Agent version: v0.2.0
If the params are not correct, a panic is thrown.

This happens when scope agent is not created (for example, when the SCOPE_DSN is not set), but from the tests it is called to SetTestCodeFromCallerSkip

An example: https://travis-ci.org/github/moby/buildkit/jobs/674337313

```
goroutine 334 [running]:
go.undefinedlabs.com/scopeagent/reflection.gopanic(0x12dba80, 0x1bc5230)
	/src/vendor/go.undefinedlabs.com/scopeagent/reflection/panic_handler.go:58 +0x145
testing.tRunner.func1(0xc000531700)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x12dba80, 0x1bc5230)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
go.undefinedlabs.com/scopeagent/reflection.gopanic(0x12dba80, 0x1bc5230)
	/src/vendor/go.undefinedlabs.com/scopeagent/reflection/panic_handler.go:58 +0x145
go.undefinedlabs.com/scopeagent/instrumentation/testing.(*Test).SetTestCode(0xc0002aa780, 0x119a8a2)
	/src/vendor/go.undefinedlabs.com/scopeagent/instrumentation/testing/testing.go:110 +0x68
go.undefinedlabs.com/scopeagent.SetTestCodeFromCallerSkip(0xc000531700, 0x1)
	/src/vendor/go.undefinedlabs.com/scopeagent/init.go:91 +0x59
github.com/moby/buildkit/util/testutil.SetTestCode(...)
	/src/util/testutil/tracing.go:17
github.com/moby/buildkit/frontend/dockerfile.testCmdShell(0xc000531700, 0x1598700, 0xc000410a00)
	/src/frontend/dockerfile/dockerfile_test.go:1635 +0x4c
github.com/moby/buildkit/util/testutil/integration.Run.func2.1(0xc000531700)
	/src/util/testutil/integration/run.go:168 +0x27c
testing.tRunner(0xc000531700, 0xc0001fe540)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/moby/buildkit/frontend/dockerfile	6.591s
FAIL
```

**Comment by tonyredondo** [comment]
Is this happening in the latest version, @fermayo did a similar fix.

**Comment by drodriguezhdez** [comment]
Yeap, v0.2.0

**Comment by tonyredondo** [comment]
Ok I’ll check
